CU-uzrm45a: Test1
ssingh-cu/CLK-1880-test pull request #64
Opened 2021-12-03 00:38 UTC by ssingh-cu

2021-12-03 00:39 UTC, mnicknish requested changes
fix this

2021-12-03 00:42 UTC, mnicknish requested changes
comment here

2021-12-03 00:43 UTC, ssingh-cu commented
Task linked: [CU-uzvfnk2 on pr review update trigger priority](https://staging.clickup.com/t/uzvfnk2)

2021-12-03 00:46 UTC, mnicknish requested changes

2021-12-03 00:46 UTC, mnicknish commented on another2
> +
please remove this line

2021-12-03 00:46 UTC, ssingh-cu reviewed
gkwadghjka

2021-12-03 00:46 UTC, ssingh-cu commented on another2
> +
please remove this line

2021-12-03 00:49 UTC, ssingh-cu commented
Task linked: [CU-uzvfnk8 this task should archive on linkage of pr](https://staging.clickup.com/t/uzvfnk8)

2021-12-22 23:31 UTC, ssingh-cu commented
Task linked: [CU-x54t1dt test 2](https://staging.clickup.com/t/x54t1dt)

2021-12-28 22:21 UTC, merged